apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-pod
  labels:
    app: Flask
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: Flask
    spec:
      containers:
        - name: myapp-pod
          image: obieh/cicdwithgithubactions:latest
  replicas: 4
  selector:
    matchLabels:
      app: Flask